### PR TITLE
Change class User to Users and fix userTokenLength issue

### PR DESCRIPTION
**Pull request by mzch**
Change class User to Users (for PostgreSQL table rename)
Fix a TokenLength bug

### CODE REVIEW

**Comment by mzch** [comment]
for #27

**Review by wzhouwzhou — CHANGES_REQUESTED** [review]
I heavily disagree - it's terrible practice to have class names plural; this would disturb the conventions in the repository. I'm sure you can change your own config to get around the issue you're having..?

**Comment by mzch** [comment]
PostgreSQL disallows `user` table. It's the system table, so you **MUST** not use `user`.

**Comment by mzch** [comment]
For example, can't access `user` using psql

**Comment by mzch** [comment]
OK. I will devide this PR.

**Comment by wzhouwzhou** [comment]
What if we added something to allow someone to change the input table name via a config? It makes sense why psql disallows user because built-in table. Perhaps we could also detect if psql is being used.

**Pull request closed without merging**
